server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:             
            - Path=/api/v1/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/course/**
        - id: enrollments
          uri: http://localhost:8070
          predicates:             
            - Path=/api/v1/enrollment/**    
        - id: certificates
          uri: http://localhost:8070
          predicates:             
            - Path=/api/v1/certificate/**
        - id: certificates
          uri: http://localhost:8070
          predicates:             
            - Path=/api/v1/certificate/**
        - id: supports
          uri: http://localhost:8070
          predicates:             
            - Path=/api/v1/support/**          
eureka:
  cliente:
    register-with-eureka: false
 
        